### ISSUE TITLE
The viewer only downloads .note file on click 

### ISSUE THREAD

**Issue by jaepil-choi** [RichardKrikler/Notability-Viewer#1]
Created `Notability.html` does not open .note files correctly. 
Instead, it just downloads .note file on click, both on Chrome and Firefox browser.

**Comment by richardkrikler** [comment]
Just as the Readme says "Notability Note Viewer for the Backup **_PDFs_** inside of a file system (e.g. with OneDrive integration in Windows).", it is only intended to be used with the Backup PDFs from the Notability-App. If your Backup-Option is set to the .note filetype, it will not be possible. You can change this setting in the Notability-App.
![grafik](https://user-images.githubusercontent.com/57064056/129794705-15ff6b9a-89e4-4b2e-b543-77d2ce75709f.png)
